# Generated by Django 3.1.3 on 2021-01-09 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('address', models.CharField(max_length=400, verbose_name='Адрес')),
                ('createdAt', models.DateField(verbose_name='Дата создания объявления')),
                ('area', models.PositiveSmallIntegerField(default=0, verbose_name='Площадь')),
                ('floor', models.PositiveSmallIntegerField(default=0, verbose_name='Этаж')),
                ('constructionAt', models.PositiveSmallIntegerField(default=2020, verbose_name='Год постройки')),
                ('done', models.BooleanField(verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('createdAt', models.DateField(verbose_name='Дата регистрации')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('login', models.CharField(max_length=300, verbose_name='Логин')),
                ('password', models.CharField(max_length=300, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('createdAt', models.DateField(verbose_name='Дата начала работы')),
            ],
            options={
                'verbose_name': 'Застройщик',
                'verbose_name_plural': 'Застройщики',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='TypeOfAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Тип объявления')),
            ],
            options={
                'verbose_name': 'Тип объявления',
                'verbose_name_plural': 'Типы объявления',
            },
        ),
        migrations.CreateModel(
            name='TypeOfArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Тип помещения')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип помещения',
                'verbose_name_plural': 'Типы помещений',
            },
        ),
        migrations.CreateModel(
            name='Сonvenience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Удобство',
                'verbose_name_plural': 'Удобства',
            },
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя')),
                ('email', models.CharField(max_length=300, verbose_name='Адрес электронная почта')),
                ('telephone', models.CharField(max_length=300, verbose_name='Телефон')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Риелтор',
                'verbose_name_plural': 'Риелторы',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=4, verbose_name='Оценка')),
                ('ad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad.ad', verbose_name='Объявление')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad.author', verbose_name='Автор оценки')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedAt', models.DateField(verbose_name='Дата обновления')),
                ('newPricece', models.CharField(max_length=4, verbose_name='Стоимость')),
                ('ad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad.ad', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Стоимость',
                'verbose_name_plural': 'Стоимости',
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad.author', verbose_name='Автор объявления'),
        ),
        migrations.AddField(
            model_name='ad',
            name='convenience',
            field=models.ManyToManyField(to='ad.Сonvenience', verbose_name='Удобства'),
        ),
        migrations.AddField(
            model_name='ad',
            name='developer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad.developer', verbose_name='Застройщик'),
        ),
        migrations.AddField(
            model_name='ad',
            name='realtor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad.realtor', verbose_name='Риелтор'),
        ),
        migrations.AddField(
            model_name='ad',
            name='typeOfAd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad.typeofad', verbose_name='Тип объявления'),
        ),
        migrations.AddField(
            model_name='ad',
            name='typeOfArea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ad.typeofarea', verbose_name='Тип площади'),
        ),
    ]
