# Generated by Django 3.1.3 on 2021-01-09 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='position',
        ),
        migrations.AlterField(
            model_name='ad',
            name='realtor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.realtor', verbose_name='Риелтор'),
        ),
        migrations.AlterField(
            model_name='price',
            name='ad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price', to='ad.ad', verbose_name='Объявление'),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Realtor',
        ),
    ]
